amazon:
  service: S3
  region: <%= ENV['AWS_REGION'] %>
  bucket: <%= ENV['AWS_STORAGE_BUCKET_NAME'] %>
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>

test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>
